Import pakietów:

In [1]:
import numpy as np
from keras import Sequential
from keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

Kodowanie wektorów:

In [3]:
wektory = pd.read_csv("dane.csv", sep=',')
wektory = np.array(wektory)
X = (wektory[:,:-1]).astype("float64") #odcięcie etykiety danych - przygotowanie "anonimowego" wektora cech
Y = wektory[:,-1] # przygotowanie wektora zawierającego tylko etykiety
integer_labeller = LabelEncoder()
Y_int = integer_labeller.fit_transform(Y)
onehot_labeller = OneHotEncoder(sparse_output=False)
Y_int = Y_int.reshape(len(Y_int),1)
Y_onehot = onehot_labeller.fit_transform(Y_int)

Podział wektorów na część testową i treningową:

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_onehot, test_size=0.3)

Tworzenie sieci:

In [5]:
network = Sequential()
network.add(Dense(10, input_dim=72, activation='sigmoid'))
network.add(Dense(3, activation='softmax'))
network.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
network.fit(X_train, Y_train, epochs=100, batch_size=10, shuffle=True)

Epoch 1/100


C:\Users\ara22\PyCharmMiscProject\.venv\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2935 - loss: 1.0887  
Epoch 2/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5151 - loss: 0.9723 
Epoch 3/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8028 - loss: 0.8923 
Epoch 4/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7144 - loss: 0.8760 
Epoch 5/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8036 - loss: 0.8369 
Epoch 6/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9078 - loss: 0.8036 
Epoch 7/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.7725 
Epoch 8/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9668 - loss: 0.7587 
Epoch 9/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9900 - loss: 0.7350 
Epoch 10/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9950 - loss: 0.7156 
Epoch 11/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.7168 
Epoch 12/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.6723 


Predykcja, transkodowanie wektorów i obliczenie macierzy pomyłek:

In [6]:
y_pred = network.predict(X_test)
y_pred_int = np.argmax(y_pred, axis=1)
y_test_int = np.argmax(Y_test, axis=1)
cm = confusion_matrix(y_test_int, y_pred_int)
print(cm)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[[14  0  0]
 [ 0 17  0]
 [ 0  0  7]]
